name: nd-mv-dmtet/geo
description: ''
tag: an_astronaut_riding_a_horse
seed: 0
use_timestamp: false
timestamp: ''
exp_root_dir: dmtet_output/tmp
exp_dir: dmtet_output/tmp/nd-mv-dmtet/geo
trial_name: an_astronaut_riding_a_horse
trial_dir: dmtet_output/tmp/nd-mv-dmtet/geo/an_astronaut_riding_a_horse
n_gpus: 1
resume: null
data_type: Dream3D-Orthogonal
data:
  batch_size: 16
  width: 1024
  height: 1024
  camera_distance_range:
  - 0.8
  - 1.0
  fovy_range:
  - 40
  - 45
  camera_perturb: 0.0
  center_perturb: 0.0
  up_perturb: 0.0
  elevation_range:
  - 5
  - 30
  azimuth_range:
  - -180
  - 180
  batch_uniform_azimuth: true
  eval_camera_distance: 3.0
  eval_fovy_deg: 40.0
  train_max_step: 1500
  train_val_check: 50
  seed: 0
  multiview_eval: true
  camera_sampling_stone: []
  cond_view: []
  relative: true
system_type: nd-dmtet-mv-system
system:
  latent_steps: 1500
  geometry_type: implicit-sdf
  geometry:
    radius: 1.0
    n_feature_dims: 0
    isosurface_resolution: 256
    isosurface_deformable_grid: true
    isosurface_coarse_to_fine: false
    shape_init: sphere
    shape_init_params: 0.5
  material_type: no-material
  material:
    n_output_dims: 0
  background_type: solid-color-background
  anneal_normal_stone:
  - 500
  - 1000
  renderer_type: nvdiff-rasterizer-dmtet
  renderer:
    context_type: cuda
    camera_space: true
    mv_bg_colors: blue
    sd_bg_colors: white
  prompt_processor_type: stable-diffusion-prompt-processor
  prompt_processor:
    pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1-base
    prompt: an astronaut riding a horse
    negative_prompt: low quality
  guidance_type: stable-diffusion-dreamtimes-guidance
  guidance:
    pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1-base
    min_step_percent:
    - 0
    - 0.5
    - 0.02
    - 1500
    max_step_percent:
    - 0
    - 0.98
    - 0.5
    - 1500
    guidance_scale: 50.0
    weighting_strategy: fantasia3d
  nd_prompt_processor_type: stable-diffusion-prompt-processor
  nd_prompt_processor:
    pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
    prompt: an astronaut riding a horse
    negative_prompt: low quality
    front_threshold: 30.0
    back_threshold: 30.0
  nd_guidance_type: nd-mv-dmtet-guidance
  nd_guidance:
    model_name: nd-mv
    ckpt_path: pretrained_models/Damo_XR_Lab/Normal-Depth-Diffusion-Model/nd_mv_ema.ckpt
    guidance_scale: 50
    min_step_percent:
    - 0
    - 0.5
    - 0.02
    - 1500
    max_step_percent:
    - 0
    - 0.98
    - 0.5
    - 1500
    recon_loss: true
    recon_std_rescale: 0.5
    weighting_strategy: fantasia3d
  loggers:
    wandb:
      enable: false
      project: threestudio
      name: None
  loss:
    lambda_sds: 1.0
    lambda_normal_consistency: 1.0
    lambda_laplacian_smoothness: 0.0
    sd_loss: 0.5
    nd_sd_loss: 1.0
    mesh_loss: 1.0
  optimizer:
    name: AdamW
    args:
      lr: 0.001
      betas:
      - 0.9
      - 0.99
      eps: 1.0e-15
trainer:
  max_steps: 1500
  log_every_n_steps: 100
  num_sanity_val_steps: 1
  val_check_interval: 50
  enable_progress_bar: true
  precision: 16-mixed
checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: 1500
